[package]
name = "burst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusoto_ec2 = "0.48.0"
rusoto_core = "0.48.0"
tokio = "1.21.2"
